name: 'build_ci'

on:
  workflow_dispatch:
    inputs:
      TARGET_ENV:
       description: 'Env to Execute scripts'
       required: true
       type: choice
       options:
         - dev
         - prd
       

    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.build_step.outputs.artifact_name }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Checkout App Version'
        run: echo "Application version $(cat version.txt)"
      - name: 'Build Application'
        id: build_step
        run: |
          VERSION=$(cat version.txt)
          ARTIFACT="artifact_${VERSION}"
          zip -r "scripts/${ARTIFACT}.zip" scripts/
          echo "artifact_name=$ARTIFACT" >> "$GITHUB_OUTPUT"
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_step.outputs.artifact_name }}
          path: scripts/*.zip

  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment: ${{ inputs.TARGET_ENV }}
      steps:
        - name: 'Download artifact'
          uses: actions/download-artifact@v4
          with:
            name: ${{ needs.build.outputs.artifact_name }}
            path: artifact
        - name: 'Extract Artifact'
          run: unzip artifact/*.zip -d extracted
        - name: 'Install PostgreSQL'
          run: |
            sudo apt-get update
            sudo apt-get install -y postgresql-client
        - name: 'Execute SQL'
          run: |
            export ${{ secrets.SUPABASE_PASSWORD }}
            psql -h "${{ secrets.SUPABASE_HOST }}" \
            -p 5432 \
            -d postgres \
            -U ${{secrets.SUPABASE_USER}} \
            -f extracted/scripts/${{ vars.SCRIPTS_PATH }}
        
          
        
       
